[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = {"path" = "../domain"}
thiserror = "2.0"
tokio = { version = "1.34.0", features = ["full"] }
env_logger = "0.11"
log = "0.4"
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
rand = "0.9"