[package]
name = "smart_house_cli_async"
version = "0.1.0"
edition = "2021"

[dependencies]
smart_house_client_async = { path = "../smart_house_client_async" }
my_stp_async = { path = "../my_stp_async" }
tokio = { version = "1", features = ["full"] }