[package]
name = "smart_house_server"
version = "0.1.0"
edition = "2021"

[dependencies]
smart_house = { path = "../smart_house" }
my_stp = { path = "../my_stp" }
thread_cancellation_token = { path = "../thread_cancellation_token" }